name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: ${{ matrix.browser }} on windows
    strategy:
      fail-fast: true
      matrix:
        browser: [chrome, firefox, webkit]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - run: yarn install
      - run: yarn run playwright
      - run: yarn run test:${{ matrix.browser }}
        env:
          STANDARD: ${{ secrets.STANDARD }}
          PASSWORD: ${{ secrets.PASSWORD }}
